# Generated by Django 3.2.12 on 2022-03-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_code', models.CharField(default=None, max_length=100, null=True)),
                ('gate_type', models.CharField(default=None, max_length=150, null=True)),
                ('camera_type', models.CharField(default=None, max_length=25, null=True)),
                ('image_path', models.TextField(default=None, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('license_plate', models.CharField(default=None, max_length=25, null=True)),
                ('tare_weight', models.CharField(default=None, max_length=20, null=True)),
            ],
        ),
    ]
