# Generated by Django 3.2.13 on 2022-05-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containerdetails',
            old_name='tare_weight',
            new_name='ISO_code',
        ),
        migrations.RenameField(
            model_name='containerdetails',
            old_name='image_path',
            new_name='image_left',
        ),
        migrations.RemoveField(
            model_name='containerdetails',
            name='camera_type',
        ),
        migrations.RemoveField(
            model_name='containerdetails',
            name='gate_type',
        ),
        migrations.RemoveField(
            model_name='containerdetails',
            name='license_plate',
        ),
        migrations.AddField(
            model_name='containerdetails',
            name='container_size',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='containerdetails',
            name='container_type',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='containerdetails',
            name='gate',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='containerdetails',
            name='image_rear',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='containerdetails',
            name='image_right',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='containerdetails',
            name='image_top',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='containerdetails',
            name='container_code',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
